# -*- coding: utf-8 -*-
"""Tarea 2.2_Leticia Soto

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rfNd9D_wCP0hn8R7oRVfo4V86y-eP5-V

# **Tarea 2.2**

Se debe calcular el número de condicionamiento para cada una de las siguientes funciones e identificar todos los valores de $x$ para los cuales $\kappa_f(x)\rightarrow\infty$ (incluyendo posiblemente los límites $x\rightarrow\pm\infty$).

#### 1. $f(x)=\tanh(x)$:

El número de condicionamiento está dado por:
$$\kappa_f(x)=\left|\frac{x f'(x)}{f(x)}\right|$$

Para la función $f(x)=\tanh(x)$, su derivada es:
$$f'(x)=\operatorname{sech}^2(x)$$

o también puede escribirse usando:
$$\operatorname{sech}(x) = \frac{1}{\cosh(x)}$$

Entonces:
$$f'(x)=\operatorname{sech}^2(x) = \frac{1}{\cosh^2(x)}$$

Por lo tanto, reemplazando se obtiene:
$$\kappa_f(x) = \left|\frac{x\,\frac{1}{\cosh^2(x)}}{\frac{\sinh(x)}{\cosh(x)}}\right|$$

Al operar queda como:
$$\kappa_f(x) = \left|\frac{x}{\sinh(x)\cosh(x)}\right|$$

Se puede simplificar aún más utilizando la siguiente identidad:
$$\sinh(2x) = 2\sinh(x)\cosh(x)$$

De ahí:
$$\sinh(x)\cosh(x) = \frac{\sinh(2x)}{2}$$

Entonces, al reemplazar se obtiene:
$$\kappa_f(x) = \left|\frac{x}{\sinh(2x)/2}\right|$$

Ahora, se debe encontrar donde $\kappa_f(x)\rightarrow\infty$.

Primero, se puede analizar dónde el denominador se hace cero, pero si $x=0$ se obtiene una indeterminación $0/0$. Por lo tanto, hay que calcular el límite.
$$\lim_{x\rightarrow0}\left|\frac{2x}{\sinh(2x)}\right|=1$$

Además,
$$\lim_{x\rightarrow\pm\infty}\left|\frac{2x}{\sinh(2x)}\right|=0$$

Por lo tanto, no existen valores de $x$ para los cuales
$\kappa_f(x)\rightarrow\infty$.

**2.** $f(x)=\frac{e^x-1}{x}$:

Como ya se comentó anteriormente, el número de condicionamiento está dado por:
$$\kappa_f(x)=\left|\frac{x f'(x)}{f(x)}\right|$$

En este caso, para

$$f(x)=\frac{e^x-1}{x}$$

Se debe calcular su derivada utilizando la regla del cociente:
$$\left(\frac{u}{v}\right)'=\frac{u'v-uv'}{v^2}$$

En este caso:
$$u=e^x-1, \qquad v=x$$

Y sus derivadas son:
$$u'=e^x, \qquad v'=1$$

Al sustituir se obtiene:
$$f'(x)=\frac{x e^x-(e^x-1)}{x^2}=\frac{e^x(x-1)+1}{x^2}$$

Y sustituyendo $f(x)$ y $f'(x)$ en la expresión del número de
condicionamiento:
$$\kappa_f(x)=\left|\frac{x\left(\frac{e^x(x-1)+1}{x^2}\right)
}{\frac{e^x-1}{x}}\right|$$

Al simplificar queda como
$$\kappa_f(x)=\left|\frac{e^x(x-1)+1}{e^x-1}
\right|$$

O de forma equivalente,
$${\kappa_f(x)=\left|\frac{x e^x}{e^x-1}-1\right|}$$

Ahora, se debe encontrar donde $\kappa_f(x)\rightarrow\infty$.

Se puede observar que en $x=0$ el denominador se anula. Sin embargo, al calcular el límite se obtiene:
$$\lim_{x\rightarrow0}\kappa_f(x)=0$$

Por lo tanto, el número de condicionamiento no tiende a infinito
cuando $x\rightarrow0$.

Por otro lado, para $x\rightarrow+\infty$, se tiene $e^x-1\approx e^x$.

Entonces:
$$\frac{x e^x}{e^x-1}\approx\frac{x e^x}{e^x}\approx x$$

Así, se obtiene:
$$
\kappa_f(x)
\approx
|x-1|.
$$

Por lo tanto:
$${\lim_{x\rightarrow+\infty}\kappa_f(x)=\infty}$$

Ahora, se analiza cuando $x\rightarrow-\infty$. Primero, se sabe que $e^x\rightarrow0$.

Además,
$$x e^x\rightarrow0, \qquad e^x-1\rightarrow-1$$

Por tanto:
$$\frac{x e^x}{e^x - 1}\rightarrow\frac{0}{-1}=0$$

Entonces:
$$\kappa_f(x)\rightarrow|0 - 1|$$

Así, se obtiene que:
$${\lim_{x \rightarrow -\infty} \kappa_f(x) = 1}$$
No diverge hacia $-\infty$.

Por lo tanto, el número de condicionamiento tiende a infinito únicamente
cuando:
$${x\rightarrow+\infty}$$

**3.** $f(x)=\frac{1-\cos(x)}{x}$:

Al igual que en el caso anterior, se debe calcular su derivada utilizando la regla del cociente:
$$\left(\frac{u}{v}\right)'=\frac{u'v-uv'}{v^2}$$

En este caso:
$$u=1-\cos(x), \qquad v=x$$

Y sus derivadas son:
$$u'=\sin(x), \qquad v'=1$$

Utilizando la regla del cociente se obtiene:
$$f'(x)=\frac{x\sin(x)-(1-\cos(x))}{x^2}$$

Sustituyendo $f(x)$ y $f'(x)$ en la expresión del número de
condicionamiento:
$$\kappa_f(x)=\left|\frac{x\left(\frac{x\sin(x)-(1-\cos(x))}{x^2}\right)
}{\frac{1-\cos(x)}{x}}\right|$$

Simplificando se tiene:
$${\kappa_f(x)=\left|\frac{x\sin(x)}{1-\cos(x)}-1\right|}$$

Ahora, se debe determinar para qué valores de $x$ el número de
condicionamiento tiende a infinito.

El denominador de la expresión se hace cero cuando:
$$1-\cos(x)=0$$

Esto implica:
$$\cos(x)=1,$$

lo cual ocurre cuando:
$$x=2k\pi,\qquad k\in\mathbb{Z}$$

Por lo tanto, se deben analizar los valores:
$$x=0,\pm2\pi,\pm4\pi,\pm6\pi,\ldots$$

Primero, se deben analizar $x\rightarrow0$. Para valores de $x$ cercanos a cero se puede utilizar las aproximaciones:
$$\sin(x)\approx x,\qquad 1-\cos(x)\approx\frac{x^2}{2}$$

Entonces:
$$\frac{x\sin(x)}{1-\cos(x)}\approx\frac{x(x)}{x^2/2}=2$$

Por lo tanto:
$$\lim_{x\rightarrow0}\kappa_f(x)=|2-1|=1$$

Así, el número de condicionamiento no tiende a infinito cuando
$x\rightarrow0$.

Ahora, se analiza el comportamiento cuando $x\rightarrow2k\pi$, con $k\neq0$.

Se considera:
$$a=2k\pi,\qquad k\neq0,$$

y se escribe un valor cercano a $a$ como:
$$x=a+h$$

donde $h\rightarrow0$.

Como $a$ es un múltiplo de $2\pi$:
$$\sin(a+h)=\sin(h)\approx h$$

y

$$1-\cos(a+h)=1-\cos(h)\approx\frac{h^2}{2}$$

Entonces:
$$\frac{x\sin(x)}{1-\cos(x)}\approx\frac{(a+h)h}{h^2/2}$$

Simplificando:
$$\frac{(a+h)h}{h^2/2}=\frac{2(a+h)}{h}$$

Como $a\neq0$, cuando $h\rightarrow0$ la magnitud de esta expresión
crece sin límite.

Por lo tanto:
$${\kappa_f(x)\rightarrow\infty\quad\text{cuando}\quad x\rightarrow2k\pi}$$

Es decir:
$${x\rightarrow\pm2\pi,\pm4\pi,\pm6\pi,\ldots}$$

Por último, se analiza el comportamiento cuando $x\rightarrow\pm\infty$.

Anteriormente, se obtuvo:
$$\kappa_f(x)=\left|\frac{x\sin(x)}{1-\cos(x)}-1\right|$$

Las funciones $\sin(x)$ y $\cos(x)$ no se acercan a un único valor cuando $x$ crece, sino que continúan oscilando cuando
$x\rightarrow\pm\infty$:
$$-1 \leq \sin(x) \leq 1,\qquad-1 \leq \cos(x) \leq 1$$

Por ejemplo, para:
$$x=(2k+1)\pi,$$

se tiene:
$$\sin(x)=0$$

y

$$\cos(x)=-1$$

Entonces:
$$\kappa_f(x)=\left|\frac{0}{2}-1\right|=1$$

Sin embargo, cerca de los valores $x=2k\pi$, el número
de condicionamiento puede crecer sin límite.

Por lo tanto, se puede decir que
$${\lim_{x\rightarrow\pm\infty}\kappa_f(x)\text{ no existe}}$$
"""