# -*- coding: utf-8 -*-
"""Tarea 4.4 Leticia Soto

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18d-ThlWVcW8xPj4RE4ZS9rDtUrTTYGbz

# **Tarea 4.4**

A partir de la definición de valor esperado de una función $F(x)$:

$$\langle F(x)\rangle=\int_{-\infty}^{\infty} F(x)\,f(x)\,dx$$

Se puede obtener el momento de orden $\ell$:

$$\langle x^\ell \rangle=\int_{-\infty}^{\infty} \rho(x)x^\ell\,dx$$

En este ejercicio se pide estudiar los casos $\ell=3$ y $\ell=4$.

### 2. Distribución simétrica respecto de
$x\to -x$:

Si la distribución es simétrica, entonces
$$\rho(-x)=\rho(x)$$

Para $\ell=3$,

$$\langle x^3 \rangle=\int_{-\infty}^{\infty}\rho(x)x^3\,dx$$

Como

$$(-x)^3=-x^3,$$

$x^3$ es una función impar.

Ya que
$$\rho(-x)=\rho(x)$$

Entonces el producto

$$\rho(x)x^3$$

es impar.

Por lo tanto, si la integral converge,

$$\langle x^3\rangle=0$$

Ya que en una integral simétrica entre $-\infty$ e $\infty$, las contribuciones de ambos lados se cancelan.

Para $\ell=4$,

$$\langle x^4 \rangle=\int_{-\infty}^{\infty}\rho(x)x^4\,dx$$

Como $x^4$ es una función par

$$(-x)^4=x^4$$

el producto $\rho(x)x^4$ también es par. Por lo tanto, las contribuciones entre cada lado no se cancelan

$$\langle x^4\rangle=2\int_0^\infty \rho(x)x^4\,dx$$

si la integral converge.

Por lo tanto, para una distribución simétrica, los momentos impares son cero si existen, mientras que los momentos pares deben por qué ser cero.

### 2. Distribución de Cauchy:

Considerando ahora la distribución de Cauchy

$$f(x)=\frac{1}{\pi}\frac{\gamma}{x^2+\gamma^2},\qquad\gamma>0$$

Primero se verifica su simetría:

$$f(-x)=\frac{1}{\pi}\frac{\gamma}{(-x)^2+\gamma^2}$$

Como

$$(-x)^2=x^2,$$

se obtiene

$$\rho(-x)=\rho(x)$$

Por lo tanto, la distribución de Cauchy es simétrica.

### 3. Momento de orden 3 para Cauchy:

Susutituyendo la definición antes obtenida para el tercer momento en Cauchy, queda:

$$\langle x^3\rangle=\int_{-\infty}^{\infty}x^3\frac{1}{\pi}\frac{\gamma}{x^2+\gamma^2}\,dx$$

Es decir,

$$\langle x^3\rangle=\frac{\gamma}{\pi}
\int_{-\infty}^{\infty}\frac{x^3}{x^2+\gamma^2}\,dx$$

Aunque el integrando es impar y se crea que el resultado es cero, hay verificar si la integral converge.

Para valores grandes de $x$,

$$x^2+\gamma^2 \approx x^2$$

Entonces,

$$\frac{x^3}{x^2+\gamma^2}\approx\frac{x^3}{x^2}=x$$

Por lo tanto, en la integral para valores grandes de $x$

$$\int_0^\infty x\,dx$$

diverge.

Por esta razón, $\langle x^3\rangle$ no existe como momento finito.

Aunque la función sea simétrica, el momento no existe porque las integrales positiva y negativa divergen por separado.

### 4. Momento de orden 4 para Cauchy:

Sustituyendo en Cauchy, el cuarto momento es

$$\langle x^4\rangle=\int_{-\infty}^{\infty}x^4\frac{1}{\pi}\frac{\gamma}{x^2+\gamma^2}\,dx$$

Es decir,

$$\langle x^4\rangle=\frac{\gamma}{\pi}
\int_{-\infty}^{\infty}\frac{x^4}{x^2+\gamma^2}\,dx$$

Para valores grandes de $x$

$$\frac{x^4}{x^2+\gamma^2}\approx
\frac{x^4}{x^2}=x^2$$

Por lo tanto, en la integral

$$\int_0^\infty x^2\,dx$$

también diverge.

Por lo tanto, $\langle x^4\rangle$ tampoco existe como momento finito.
"""