# -*- coding: utf-8 -*-
"""Tarea _3.4_Leticia_Soto

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZIvqyNie1c4BewWMnyj0eZ2XE-cKdtse

# **Tarea 3.4**

El enunciado dice lo siguiente:

*   $20\%$ de la población tiene la enfermedad
*   Si tiene la enfermedad, el examen da positivo el $90\%$ de las veces
*   Si no tiene la enfermedad, igualmente puede dar positivo el $30\%$ de las veces (falso positivo)
*   Solo las personas que dan positivo reciben la droga
*   Esta droga produce manchas rojas solo en el $20\%$ de quienes la reciben

Ahora, si una persona tiene esas manchas rojas. ¿Cuál es la probabilidad de que haya tenido la enfermedad?

Entonces, se quiere saber P(Enfermedad | Manchas).

A modo de hacer esto más cómodo, se definirá lo siguiente:

*   $E$: persona que tiene la enfermedad
*   $NE$: persona que no tiene la enfermedad
*   $P$: persona que dio positivo
*   $M$: persona que presentó manchas

Del enunciado se puede obtener lo siguiente:

*   $P(E)=0.20$
*   $P(NE)=1-P(E)=0.80$
*   $P(P|E)=0.90$
*   $P(P|NE)=0.30$
*   $P(M|P)=0.20$

Y se quiere saber $P(E|M)$.

Para resolver este problema, se debe utilizar el Teorema de Bayes:

$$P(E|M)=\frac{P(M|E)P(E)}{P(M)}$$

Primero, hay que calcualar $P(M|E)$. Para que una persona enferma presente manchas, debe obtener un resultado positivo y luego desarrollar las manchas debido a la droga:

$$P(M|E)=P(P|E)P(M|P)$$

Reemplazando los valores:
$$P(M|E)=(0.90)(0.20)=0.18$$

Ahora, se debe calcular la probabilidad de presentar manchas sin tener la enfermedad:

$$P(M|NE)=P(P|NE)P(M|P)$$

Reemplazando:
$$P(M|NE)=(0.30)(0.20)=0.06$$

Para poder obtener la probabilidad total de presentar manchas, hay que considerar las dos posibilidades: tener o no tener la enfermedad.

$$P(M)=P(ME)+P(MNE)$$
$$P(M)=P(M|E)P(E)+P(M|NE)P(NE)$$

Sustituyendo:
$$P(M)=(0.18)(0.20)+(0.06)(0.80)$$

$$P(M)=0.036+0.048=0.084$$

Finalmente, aplicando el Teorema de Bayes se obtiene:

$$P(E|M)=\frac{(0.18)(0.20)}{0.084}=0.4286$$

Por lo tanto, la probabilidad de que una persona que presenta manchas rojas haya tenido la enfermedad es aproximadamente:
$${42.86\%}$$
"""