# -*- coding: utf-8 -*-
"""Tarea 1.7 Leticia Soto

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qm42kKG9oMTUQKLr_3pbCzFxP_XoIcFA

# **Tarea 1.7**
"""

import numpy as np       # Importamos la biblioteca

# Se crea un arreglo con los valores de n desde 1 hasta 100
n = np.arange(1, 101)

# Se evalúa el término e^n(n+1) para cada n y sumamos todos los resultados
suma = np.sum(np.exp(n) * (n + 1))

# Se muestra el valor final de la sumatoria
print(suma)